services:
  - type: web
    name: fastapi-ocr-api # You can change this name
    env: python # Use 'env: python' for Render's Python environment
    plan: free # Or your preferred plan
    autoDeploy: false # Set to true to auto-deploy on pushes to your main branch
    
    # Region where your service will be hosted
    # region: oregon # Example: oregon, frankfurt, singapore. Pick one close to you/your users.

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
